general_settings:
  ## MANDATORY. Name of your nextcloud docker container. It most probably should be: nextcloud
  nextcloud_container_name: <INSERT YOUR NEXTCLOUD CONTAINER NAME HERE>

## DELETE THE ONE YOU DON'T NEED. This is the schedule when you want the script to run and make backup / update
backup_schedule:
  ## DELETE IF NOT NEEDED
  weekly:
    ## available values are MON, TUE, WED, THU, FRI, SAT, SUN.
    day: <INPUT DAY HERE>
    ## Use HH:mm format and wrap the time in quatation marks e.g. "14:28"
    time: <HH:mm>
  ## DELETE IF NOT NEEDED
  daily:
    ## Use HH:mm format and wrap the time in quatation marks e.g. "14:28"
    time: <HH:mm>
  ## DELETE IF NOT NEEDED. This schedule will run the backup/update procedure, on the specified day on the last week of the current month
  last_day_of_month:
    ## available values are MON, TUE, WED, THU, FRI, SAT, SUN.
    day: <INPUT DAY HERE>
    ## Use HH:mm format and wrap the time in quatation marks e.g. "14:28"
    time: <HH:mm>
